import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  OVERSIZE_LINES, isGenerated, isOversized, parseGitattributesGenerated,
} from '../src/domain/git/classify';

// --- Generated by the shape of the path ---

test('a lockfile is generated, by name and by suffix', () => {
  for (const path of [
    'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'Cargo.lock',
    'apps/web/package-lock.json', 'flake.lock',
  ]) {
    assert.equal(isGenerated(path), true, path);
  }
});

test('build output is generated wherever it sits', () => {
  for (const path of ['dist/index.js', 'packages/ui/dist/index.js', 'out/main.js', '.next/server/page.js']) {
    assert.equal(isGenerated(path), true, path);
  }
});

test('`build` and `app` count only at the top, where a bundler puts them', () => {
  assert.equal(isGenerated('app/main.js'), true);
  assert.equal(isGenerated('build/icon.png'), true);
  // This repository keeps its renderer bootstrap in src/renderer/app/ and real
  // source in src/build-tools/: the benefit of the doubt goes to the source.
  assert.equal(isGenerated('src/renderer/app/bootstrap.ts'), false);
  assert.equal(isGenerated('src/build/steps.ts'), false);
});

test('a bundle is generated, a file that merely mentions one is not', () => {
  assert.equal(isGenerated('public/vendor.min.js'), true);
  assert.equal(isGenerated('public/app-bundle.js'), true);
  assert.equal(isGenerated('src/bundle-loader.ts'), false);
  assert.equal(isGenerated('src/minify.ts'), false);
});

test('ordinary source is not generated, including a directory that shares a name', () => {
  for (const path of ['src/app.ts', 'README.md', 'test/dist-check.test.ts', 'dist']) {
    assert.equal(isGenerated(path), false, path);
  }
});

// --- Generated because the repository says so ---

test('a `.gitattributes` entry marking a path generated wins on its own', () => {
  const attributes = parseGitattributesGenerated([
    '# what the repository considers output',
    'schema.graphql linguist-generated',
    'src/api/*.gen.ts linguist-generated=true',
  ].join('\n'));

  assert.equal(isGenerated('schema.graphql', attributes), true);
  assert.equal(isGenerated('src/api/client.gen.ts', attributes), true);
  assert.equal(isGenerated('src/api/client.ts', attributes), false);
  assert.equal(isGenerated('src/app.ts', attributes), false);
});

test('a pattern without a slash matches the basename at any depth', () => {
  const attributes = parseGitattributesGenerated('*.pb.go linguist-generated\n');
  assert.equal(attributes('api.pb.go'), true);
  assert.equal(attributes('internal/rpc/api.pb.go'), true);
  assert.equal(attributes('internal/rpc/api.go'), false);
});

test('a pattern with a slash is anchored to the repository root', () => {
  const attributes = parseGitattributesGenerated('docs/api.md linguist-generated\n');
  assert.equal(attributes('docs/api.md'), true);
  assert.equal(attributes('web/docs/api.md'), false);
});

test('`*` stops at a separator and `**` crosses it, including none of it', () => {
  const single = parseGitattributesGenerated('src/*.js linguist-generated\n');
  assert.equal(single('src/app.js'), true);
  assert.equal(single('src/deep/app.js'), false);

  const double = parseGitattributesGenerated('src/**/*.js linguist-generated\n');
  assert.equal(double('src/deep/app.js'), true);
  assert.equal(double('src/app.js'), true, '`/**/` matches no directory at all too');
  assert.equal(double('other/app.js'), false);
});

test('a directory pattern claims everything under it', () => {
  const attributes = parseGitattributesGenerated('generated/ linguist-generated\n');
  assert.equal(attributes('generated/client.ts'), true);
  assert.equal(attributes('generated/deep/client.ts'), true);
  assert.equal(attributes('src/client.ts'), false);
});

test('the last matching line wins, so a broad rule can be carved into', () => {
  const attributes = parseGitattributesGenerated([
    'src/api/* linguist-generated',
    'src/api/handwritten.ts -linguist-generated',
  ].join('\n'));
  assert.equal(attributes('src/api/client.gen.ts'), true);
  assert.equal(attributes('src/api/handwritten.ts'), false);
});

test('a `.gitattributes` with nothing to say about generated files says nothing', () => {
  const attributes = parseGitattributesGenerated('* text=auto\n*.png binary\n');
  assert.equal(attributes('anything.png'), false);
  assert.equal(isGenerated('src/app.ts', attributes), false);
});

test('a quoted pattern keeps its spaces', () => {
  const attributes = parseGitattributesGenerated('"docs/my notes.md" linguist-generated\n');
  assert.equal(attributes('docs/my notes.md'), true);
});

test('comments, blank lines and unreadable lines are skipped rather than matched', () => {
  const attributes = parseGitattributesGenerated('\n# a comment\n\nreal.txt linguist-generated\n');
  assert.equal(attributes('real.txt'), true);
  assert.equal(attributes('# a comment'), false);
});

// --- Too big to render unasked ---

test('oversize is additions plus deletions, over the threshold rather than at it', () => {
  assert.equal(isOversized({ additions: 300, deletions: 201 }), true);
  assert.equal(isOversized({ additions: OVERSIZE_LINES, deletions: 0 }), false);
  assert.equal(isOversized({ additions: OVERSIZE_LINES + 1, deletions: 0 }), true);
  assert.equal(isOversized({ additions: 0, deletions: 0 }), false);
});

test('the threshold can be moved, because 500 is a judgement and not a law', () => {
  assert.equal(isOversized({ additions: 10, deletions: 0 }, 5), true);
  assert.equal(isOversized({ additions: 10, deletions: 0 }, 50), false);
});
